
set nocompatible              " be iMproved, required

source ~/bundles.vim

syntax on

"Information on the following setting can be found with
":help set
set ts=4
set et
set autoindent 
set sw=4  "this is the level of autoindent, adjust to taste
set ruler
set number
set backspace=indent,eol,start
set visualbell
set termguicolors
" Uncomment below to make screen not flash on error
" set vb t_vb=""

set sts=4

" Highlight search patterns
set hlsearch

" Let airline show by default
set laststatus=2

" Change colorscheme
colorscheme gruvbox
let g:gruvbox_italic=1
set background=dark

" Make the ',' be the 'command modifier'
let mapleader = ","

" Turn on RainbowParentheses
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" Turn on XML syntax folding
let g:xml_syntax_folding=1
au FileType xml setlocal foldmethod=syntax

" Change pylint executable
let g:ale_python_pylint_executable="pylint3.6"

" Add mapping for fzf
map <Leader>f :FZF<CR>

" Use ag for the ack plugin
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" Silence vim's grep on the terminal
function! Search(string) abort
  let saved_shellpipe = &shellpipe
  let &shellpipe = '>'
  try
    execute 'Ack!' shellescape(a:string, 1)
  finally
    let &shellpipe = saved_shellpipe
  endtry
endfunction

" Use Ack! so we don't auto open files and shortcut it
cnoreabbrev Ack Ack!
nnoremap <Leader>a :call Search('')<left><left>

" Add CamelCaseMotion to default motion
call camelcasemotion#CreateMotionMappings('<leader>')

map <S-DEL> <BS>

" F2 for paste mode
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

nnoremap <F3> :set number!<CR>

" Disable comment continuation
set formatoptions-=r formatoptions-=o

" Set rainbow parens colors
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
